language: java
jdk: oraclejdk7
notifications:
  email: false
install:
- "./travis/install-prerequisites.sh"
script:
- "./travis/build.sh"
after_success: "./travis/deploy.sh"
env:
  global:
  - BINTRAY_USER=bploeckelman
  - BINTRAY_REPO=LudumDare
  - secure: HfHtsvuZSVCycxgUrPuR3kAcKxCBp3Kq0TG+S6wNEStgdIPKoGpIZNNflzkXNSWLnveeHoTyahKNBij9q7bbRvGMw98u49Z7L5OeZNYGfw3UM0cvbpEGtMl5kTy475R0z+P4Ve7uKSyFoubwAD6ExQZ1+6tZXSTeCh4ABtGRczBhejg5yZKOLUeY7W7oztjdtSsElTJdaRkmahpCK6r+efAsPKY/WZhPZhOFhPs5MsKDJjh9CI9pESjmyM//5OHXiPU/H0VovAb/YmDnFESSjx0M/LtSj0/vLYbWKEj6CBGNMFCaij5DLjd8o6fRczIdrJRIYpQlItWTm2onGvzUoUI7qzEveqqZe0ZcWP7FBeczYOA1tTymgX2iAAZpuQ5/w7CKBuoVCxMOnG1v6qeLvtR+6yYo/HwN1defFNmCrG5WGJGM6/14Q5YVc0PIGeGM+yNVcwDpG+QjEb9hGN5ODzBpdo3vM0AWv5hSIp5blw8fBBzbOr9+k6RZAVRuCvJtZBnhYXWsgL7ohXwxxdnodbmURh57cexagvvL5ojrnjQRpW09fw74mTtq5OVWDMHLdBUJ9hxiN5zDiVSgR/dcK0B58wG+kYG8rjL7TlEXD8NRqWVw6ZmAu1Jc1x25r3CEqMB9xpBNZ5eFH40koDnjCjzJI2nJZkFq9CK8W8wUtrI=
cache:
  directories:
  - "$HOME/.gradle/caches"
  - "$HOME/.gradle/wrapper"
  - travis/android-sdk-linux
before_cache:
- rm -f "$HOME/.gradle/caches/modules-2/modules-2.lock"
