language: java
jdk: oraclejdk7
notifications:
  email: false
install:
- "./travis/install-prerequisites.sh"
script:
- "./travis/build.sh"
after_success: "./travis/deploy.sh"
env:
  global:
  - BINTRAY_USER=bploeckelman
  - BINTRAY_REPO=LudumDare
  - secure: RH7TGfqWsv5Bc5l3zX8xVBED+ydjyx7XL9EWvH/tYq+3jrr7NkkUl+MWxiGt623UBYhjyArI7x3UVBCeKr1l36v7U9EE2o4y80re9LibfWp/Xr1MXbQjHxk94ckLDOP3XLOXf6BqWnUeN3Sd7oQPXQ+pNcdIZvzQ5hMRI0r/jFQ8Q0hC9eaZMDO7Zqb9/r7wy1SsV//3YJpgFzBGrRxBzoEVKQCIR0AhotRWTMODro0wrf6+JhIvaXRLyXJHiPFighiXSk6iKeD5w5QvnMnBcjyuF8QP9xu8vL9Ol6MdKZlSh2mMKhHL53lcHgGNT+249RAC+PzVNRqhQl2XBn4sOHgwlZyGn1UOspn5GFojcFzLeZZjq9d2aszQCLqM7hzpV495L1MzjHAIR3mFFQTP2FLtTHu2kYQh1408rL9fhqX5jUTI1kYbyJJWQSDhviqY7AkPdiN1Wr8/EDht1/75zCw4f7d0yJqA1BUNY2CfnIAXzKEO6RpvedZfHblCRZJ/EdU2/4nNKxd7pFgCm7Gk1L/v9sCsXSs/FsRDcIS23VdC74TJxYXjccMlX/MaxRFRtFdtkXrOUUgOJ0zSMWO+OB8Yiextq9sS1j62Ljr6YkL6ttC4+/+VLl+2VzaIjF3QrFABZOON/wYcfdnow9LD8/mLHmtQk62qmm65iQN97tY=
cache:
  directories:
  - "$HOME/.gradle/caches"
  - "$HOME/.gradle/wrapper"
  - travis/android-sdk-linux
before_cache:
- rm -f "$HOME/.gradle/caches/modules-2/modules-2.lock"
deploy:
  key:
    secure: TOi3s6DYTQlpqa+iAifzxTtwvlhBcC2mZiSU1zSk1z259inuUfOaJutfb42y332C/TqM/NiUGbiKCLfbzLDN/84/vv2ZSZHO4eEqKh97RXfLzESNE6rmdLUiaCHEmR9jMAUfJzTje4n32bun9jJ4KqEzy9gh31z+PAUzw7koh8SXfmMuY71kApKLGbsTiEAW4IZz432/kdhQO87E1j/epvQPg9teh3CPZN4sz04GLQEbkSOwi5acVXdWEso6gmQq2o9VlWBB/QeIkGwzdtPs9oYzfHGB3tMWO+ZAZqSY4DlCuYi+MrOtz0iTDSMnU7PzEELbwaIPXFE+pAuyUf+WL1xxpBWgHBb+yruBLiUUgEkVAV6SNxFZ+AAtsXH+4E+GWc37cX6kaYSNRjSVwV7wkiLwDvUgvsqqkZY094/UK32nk+ctQr4GN/9DkDQ2RW41G7m/sjDdbgUPJZL6pkAN/4Op3AlqnABMkMrCoqmy6I74XD9XhuYVjROahCs9Cnp3TtVrAcy2Q9I3l/9ENjGzmKO/6vGdld2Ca3nHgCKS9Gv9zoE7EQ49my2vQWAmZ24OOEwevIESwrHttiUmYnMdo/ta+BdBtAERYsckGbxLEUXCJBzD44n0OM3dRRC1zx+c5PXpLNARs1Dy/cx8wr6AxfFII3sQvJtQ/dVkuanju9Y=
