language: java
jdk: oraclejdk7
notifications:
  email: false
install:
- "./travis/install-prerequisites.sh"
script:
- "./travis/build.sh"
after_success: "./travis/deploy.sh"
env:
  global:
    secure: hAdiony0Fu09i4WicwmU0mRjAw4tdf39OW9kTOrJXL8Eg/2QWTYTCSbxEfXaCKF3ZFCE0ZN+pmovSPL2xY82QHCARqfZ9rUQJMrdRTMSAC4Hm47kJXoxoAl6LRlhY1P/WvnqOa2ZRBQj24/JzYhj4EOTxbxXyf5S0nMmpbTIvOauLVqwcaBEpVywd34fd9w1ZEw9eMkf4YLVyvkwzy9+lWGW2ESGCKL0BUfYlbzhwgtUvOzdv8dZQpaWsIcbn1V+BLy2eUiU7yNktOJqGc6/jHkOCqxsIBPp1NGmy/q1DlvIs1TwBDJWfU+OY9Ih3Qt1TxUBRtvKyKNojkisE4WJ5esI3UKN+JJ5Sdd68Zx1dVBa749q8i6tFzd2xwyZ2YYfuQvytCdgCUaykbZMg5Jwfqldayosvj8MHNn9GxNPsqdF0z+7le08rtl8455gBlelC7JP0JeiOMn21Dy8ygWvYXq2lM7szPT7f3MGUOiEtQb6bSgCnIeL1UiCJZWSgIR+as7RpHUFe1NBbwLNa1CUzG2EXj3qCdZwDVzSNJbi2aL1zUuzImxNuF8jucKg5pEYWkUf3GltXBGgH9Myz+Qu2E3H2l/QimWhtlvStKTnI6XjQOCDsmx3V2JeqVSOsifggfuagiOIbCkfiVjGcGWaCn362zFxf7AaWkBhxpR3Z/I=
cache:
  directories:
  - "$HOME/.gradle/caches"
  - "$HOME/.gradle/wrapper"
  - travis/android-sdk-linux
before_cache:
- rm -f "$HOME/.gradle/caches/modules-2/modules-2.lock"
